export { default as HomePage } from './home'
export { default as AboutPage } from './about'
export { default as ProjectsPage } from './projects'
export { default as StreakPage } from './streak'
export { default as ProjectDetailPage } from './projectDetail'
